### PR TITLE
add security policy resource support to the TMC terraform provider

### PR DESCRIPTION
**Pull request by ishangupta-ds**
1. **What this PR does / why we need it**: This PR adds security policy resource support to the TMC terraform provider.

2. **Additional information**: All changes were reviewed before merging to the feature branch. This is a promotion PR.

### CODE REVIEW

**Review by shreyassreenivas — DISMISSED** [review]

**Comment by shobha2626** [comment]
Could you please split the commit into logical parts, as it will be shown up while a release is made. 

We can have commits something like -
1. Add security policy resource support
2. Add unit test for security policy resource
3. Acceptance test for security policy resource
4. Documentation for security policy

**Comment by ishangupta-ds** [comment]
> Could you please split the commit into logical parts, as it will be shown up while a release is made.
> 
> We can have commits something like -
> 
> 1. Add security policy resource support
> 2. Add unit test for security policy resource
> 3. Acceptance test for security policy resource
> 4. Documentation for security policy

This might cause a huge amount of lines of code and number of file changes for some commits. Should I go ahead with it?

**Comment by shobha2626** [comment]
> > Could you please split the commit into logical parts, as it will be shown up while a release is made.
> > We can have commits something like -
> > 
> > 1. Add security policy resource support
> > 2. Add unit test for security policy resource
> > 3. Acceptance test for security policy resource
> > 4. Documentation for security policy
> 
> @shobha2626 This might cause a huge amount of lines of code and number of file changes for some commits. Should I go ahead with it?
> 
> This was done as per - [#53 (comment)](https://github.com/vmware/terraform-provider-tanzu-mission-control/pull/53#issuecomment-1206376807)
> 
> cc: @shreyassreenivas @Vasundharashukla

I think this wouldn't cause huge changes, squashing the commit and choosing the right files as per the commit message should suffice. This is one resource and having n commits seems a little too much. 

Maybe further divide into -

- Add client and model for security policy resource
- Add schema for security policy
- Add CRUD support for security policy
- Add unit test for security policy resource
- Acceptance test for security policy resource
- Documentation for security policy

**Review by shobha2626 — APPROVED** [review]
LGTM

**Pull request merged**
