### PR TITLE
Fix x509 issues

### PR DESCRIPTION
**Pull request by warroyo**
1. **What this PR does / why we need it**:

This removes the hard coded root cert and allows the system store to be used to trust certs unless root CAs are explicitly provided

### CODE REVIEW

**Comment by ysineil** [comment]
please merge, we're experiencing this issue.

**Comment by warroyo** [comment]
@ysineil a quick workaround until this is merged is to set insecure_allow_unverified_ssl=true  in the provider config.

**Comment by ysineil** [comment]
confirmed

**Comment by GantzGit** [comment]
fixes #409

**Review by AkbaraliShaikh — APPROVED** [review]

**Comment by sbasu31** [comment]
Approved

**Review by sbasu31 — APPROVED** [review]

**Pull request merged**
