### PR TITLE
Remove TSM integration support

### PR DESCRIPTION
**Pull request by vivgoyal**
### Summary

Removes TSM integration support.

### Type

- [ ] This is a bug fix.
- [ ] This is an enhancement or feature.
- [ ] This is a code style/formatting update.
- [ ] This is a documentation update.
- [ ] This is a refactoring update.
- [ ] This is a chore update
- [x] This is something else.
      Please describe: Removal of a feature

### Breaking Changes?

- [x] Yes, there are breaking changes.
- [ ] No, there are no breaking changes.

### Test and Documentation

- [ ] Tests have been completed.
- [ ] Documentation has been added or updated.

### Additional Information

Signed-off-by: Vivek Goyal <vivek.goyal@broadcom.com>

### CODE REVIEW

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
If I recall, there are some references to `integrations` in the `Makefile`, `.github/workflows/release.yml`, and `.github/workflows/tests.yml` that may need an update.

**Comment by vivgoyal** [comment]
> If I recall, there are some references to `integrations` in the `Makefile`, `.github/workflows/release.yml`, and `.github/workflows/tests.yml` that may need an update.

fixed

**Review by tenthirtyam — CHANGES_REQUESTED** [review]
**Nit**: Could you update the commit signing to our `broadcom.com` emails (assuming attached to your profile) since our `vmware.com` addresses are now decommissioned?

**Comment by vivgoyal** [comment]
> **Nit**: Could you update the commit signing to our `broadcom.com` emails (assuming attached to your profile) since our `vmware.com` addresses are now decommissioned?

Done

**Review by tenthirtyam — APPROVED** [review]
LGTM!

**Pull request merged**
