### PR TITLE
Update custom policy documentation

### PR DESCRIPTION
**Pull request by Vasundharashukla**
1. **What this PR does / why we need it**:

Update custom policy documentation to define the custom policy usage via the Terraform provider. The documentation now mentions that currently the provider supports the pre-defined custom policy recipes.

### CODE REVIEW

**Review by ishangupta-ds — APPROVED** [review]
LGTM!

**Comment by shreyassreenivas** [comment]
@Vasundharashukla , it slipped my mind that we have a tmpl, and the docs are generated from this template. 
recently some of the docs have been directly updated but the template is not, can you take care of this

**Comment by Vasundharashukla** [comment]
> @Vasundharashukla , it slipped my mind that we have a tmpl, and the docs are generated from this template.
> recently some of the docs have been directly updated but the template is not, can you take care of this

Please point to the docs that have been updated in this way, also open a task for it.

**Comment by shreyassreenivas** [comment]
> > @Vasundharashukla , it slipped my mind that we have a tmpl, and the docs are generated from this template.
> > recently some of the docs have been directly updated but the template is not, can you take care of this
> 
> Please point to the docs that have been updated in this way, also open a task for it.

Follow the last few commits which went in to update the EKS docs or take a diff between the EKS docs and the template. 
It should be a very small task so not sure you need a task for it, but I would leave it to you if you want to create one

**Comment by Vasundharashukla** [comment]
> > > @Vasundharashukla , it slipped my mind that we have a tmpl, and the docs are generated from this template.
> > > recently some of the docs have been directly updated but the template is not, can you take care of this
> > 
> > 
> > Please point to the docs that have been updated in this way, also open a task for it.
> 
> Follow the last few commits which went in to update the EKS docs or take a diff between the EKS docs and the template. It should be a very small task so not sure you need a task for it, but I would leave it to you if you want to create one

Since it is updating the template files and not in the scope of the current custom policy doc fix, will open a separate PR with changes for all template file updates. Let's not make this PR dependant.

**Comment by shreyassreenivas** [comment]
> > > > @Vasundharashukla , it slipped my mind that we have a tmpl, and the docs are generated from this template.
> > > > recently some of the docs have been directly updated but the template is not, can you take care of this
> > > 
> > > 
> > > Please point to the docs that have been updated in this way, also open a task for it.
> > 
> > 
> > Follow the last few commits which went in to update the EKS docs or take a diff between the EKS docs and the template. It should be a very small task so not sure you need a task for it, but I would leave it to you if you want to create one
> 
> Since it is updating the template files and not in the scope of the current custom policy doc fix, will open a separate PR with changes for all template file updates. Let's not make this PR dependant.

sure, ensure that you raise an MR and get it fixed.

**Review by shreyassreenivas — APPROVED** [review]

**Pull request merged**
